//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Gestion_Des_Conges_2
{
    using System;
    using System.Collections.Generic;
    
    public class LMLeaveHistory
    {
        [Display(Name = "Leave request Id:")]
        [Required(ErrorMessage = "The leave request Id is required")]
        public int LeaveId { get; set; }

        [Display(Name = "Employee Id:")]
        [Required(ErrorMessage = "The employee Id is required")]
        public int EmpId { get; set; }

        [Display(Name = "Application Date:")]
        [Required(ErrorMessage = "The application date is required")]
        public System.DateTime ApplicationDate { get; set; }

        [Display(Name = "Leave start date:")]
        [Required(ErrorMessage = "The leave start date is required")]
        public System.DateTime LeaveStartDate { get; set; }

        [Display(Name = "Leave end date:")]
        [Required(ErrorMessage = "The leave end date is required")]
        public System.DateTime LeaveEndDate { get; set; }

        [Display(Name = "Leave type:")]
        [Required(ErrorMessage = "The leave type is required")]
        public string LeaveType { get; set; }

        [Display(Name = "Leave description:")]
        public string LeaveDesc { get; set; }

        [Display(Name = "Leave request state:")]
        [Required(ErrorMessage = "The leave request state is required")]
        public string LeaveState { get; set; }

        public string StateReason { get; set; }
    
        public virtual LMEmployee LMEmployee { get; set; }
    }
}
