//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Gestion_Des_Conges
{
    using System;
    using System.Collections.Generic;
    
    public class LMEmployee
    {
        public LMEmployee()
        {
            this.LMEmployees1 = new HashSet<LMEmployee>();
            this.LMLeaveHistories = new HashSet<LMLeaveHistory>();
        }


        [Display(Name = "Employee Id:")]
        [Required(ErrorMessage = "The employee Id is required")]
        public int EmpId { get; set; }

        [Display(Name = "Employee First name:")]
        [Required(ErrorMessage = "The employee first name is required")]
        public string EmpFName { get; set; }

        [Display(Name = "Employee lastname:")]
        [Required(ErrorMessage = "The employee lastname is required")]
        public string EmpLName { get; set; }

        
        [Display(Name = "Date of birth:")]
        [Required(ErrorMessage = "The date of birth is required")]
        //[DataType(DataType.Date)]
        public System.DateTime DateOfBirth { get; set; }

        [Display(Name = "Employee manager Id:")]
        [Required(ErrorMessage = "The manager Id is required")]
        public int ManagerEmpId { get; set; }

        [Display(Name = "Grade:")]
        [Required(ErrorMessage = "The grade is required")]
        public string Grade { get; set; }

        [Display(Name = "Sex:")]
        [Required(ErrorMessage = "The sex is required")]
        public string Sex { get; set; }

        [Display(Name = "Telephone:")]
        [Required(ErrorMessage = "The telephone is required")]
        public string Tel { get; set; }

        [Display(Name = "Sick leave balance (days):")]
        [Range(1,30)]
        [Required(ErrorMessage = "The leave balance is required")]
        public int SickLeaveBalance { get; set; }


        [Display(Name = "Earened leave balance(days):")]
        [Range(0,30)]
        [Required(ErrorMessage = "The earened leave balance is required")]
        public int EarnedLeaveBalance { get; set; }

        [Display(Name = "E-mail:")]
        [Required(ErrorMessage = "The e-mail Id is required")]
        public string Email { get; set; }

        [Display(Name = "Password:")]
        [Required(ErrorMessage = "The password: is required")]
        public string Pass { get; set; }



        public virtual ICollection<LMEmployee> LMEmployees1 { get; set; }
        public virtual LMEmployee LMEmployee1 { get; set; }
        public virtual ICollection<LMLeaveHistory> LMLeaveHistories { get; set; }
    }
}
