//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Des_Conges
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMLeaveHistory
    {
        public int LeaveId { get; set; }
        public int EmpId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public System.DateTime LeaveStartDate { get; set; }
        public System.DateTime LeaveEndDate { get; set; }
        public string LeaveType { get; set; }
        public string LeaveDesc { get; set; }
        public string LeaveState { get; set; }
        public string StateReason { get; set; }
    
        public virtual LMEmployee LMEmployee { get; set; }
    }
}
