//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jour6_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bug()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateBug { get; set; }
        public int PersonID { get; set; }
        public int ProjectID { get; set; }
        public int Priorite { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
    
        public virtual Statut Statut { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual Projet Projet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
