//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jour6_EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibitracEntities : DbContext
    {
        public bibitracEntities()
            : base("name=bibitracEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bug> Bugs { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Projet> Projets { get; set; }
        public virtual DbSet<Statut> Statuts { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
    }
}
