//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jour6_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public System.DateTime DateTicket { get; set; }
        public int PersonID { get; set; }
        public string Message { get; set; }
        public int BugID { get; set; }
        public int StatusID { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual Bug Bug { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual Statut Statut { get; set; }
    }
}
